apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-service
  template:
    metadata:
      labels:
        app: add-service
    spec:
      containers:
        - name: add-service
          image: luisacelis/taller-siete:add_service_v1.0.0
          ports:
            - containerPort: 8081
          env: # Setting Enviornmental Variables
            - name: DATABASE_URL
              value: "jdbc:postgresql://database-service:5432/postgres"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
